import { z } from "zod";

export const itSchema = z.object({
  country: z.literal("it"),
  homePrice: z.number().positive(),
  downPaymentPct: z.number().min(0).max(1),
  mortgageRate: z.number().min(0).max(0.5),
  termYears: z.number().int().positive().max(40),
  horizonYears: z.number().int().positive().max(40),
  closingCostsPct: z.number().min(0).max(0.2),
  appreciationPct: z.number().min(-0.2).max(0.5),
  maintenancePct: z.number().min(0).max(0.1),
  insuranceAnnual: z.number().min(0),
  hoaMonthly: z.number().min(0),
  monthlyRent: z.number().min(0),
  rentInflationPct: z.number().min(-0.1).max(0.5),
  cpiPct: z.number().min(-0.1).max(0.5),
  equityReturnPct: z.number().min(-0.5).max(0.5),
  bondReturnPct: z.number().min(-0.5).max(0.5),
  equitySplit: z.number().min(0).max(1),
  cadastralValue: z.number().positive(),
  notaryPct: z.number().min(0).max(0.1),
  agentPct: z.number().min(0).max(0.1),
  agentIvaPct: z.number().min(0).max(0.5),
  tariAnnual: z.number().min(0),
  registrationTaxRate: z.number().min(0).max(0.2),
  fixedIpotecariaCatastale: z.number().min(0),
  bolloRate: z.number().min(0).max(0.05),
  mutuoDeductionRate: z.number().min(0).max(0.5),
  mutuoInterestCap: z.number().min(0),
  equityCgtRate: z.number().min(0).max(0.5),
  bondCgtRate: z.number().min(0).max(0.5),
  mutuoInterestCapGrowthPct: z.number().min(-0.2).max(0.5),
}).refine((d) => d.horizonYears <= d.termYears, {
  message: "horizon must be ≤ mortgage term",
  path: ["horizonYears"],
});
