import { z } from "zod";

export const nlSchema = z.object({
  country: z.literal("nl"),
  homePrice: z.number().positive(),
  downPaymentPct: z.number().min(0).max(1),
  mortgageRate: z.number().min(0).max(0.5),
  termYears: z.number().int().positive().max(40),
  horizonYears: z.number().int().positive().max(40),
  closingCostsPct: z.number().min(0).max(0.2),
  appreciationPct: z.number().min(-0.2).max(0.5),
  maintenancePct: z.number().min(0).max(0.1),
  insuranceAnnual: z.number().min(0),
  hoaMonthly: z.number().min(0),
  monthlyRent: z.number().min(0),
  rentInflationPct: z.number().min(-0.1).max(0.5),
  cpiPct: z.number().min(-0.1).max(0.5),
  equityReturnPct: z.number().min(-0.5).max(0.5),
  bondReturnPct: z.number().min(-0.5).max(0.5),
  equitySplit: z.number().min(0).max(1),
  wozValue: z.number().positive(),
  partnered: z.boolean(),
  marginalRate: z.number().min(0).max(0.6),
  hraCeilingRate: z.number().min(0).max(0.6),
  ozbRate: z.number().min(0).max(0.05),
  ewfRateLow: z.number().min(0).max(0.05),
  ewfRateHigh: z.number().min(0).max(0.1),
  ewfHighThreshold: z.number().min(0),
  box3Threshold: z.number().min(0),
  box3DeemedYield: z.number().min(0).max(0.2),
  box3TaxRate: z.number().min(0).max(0.6),
  transferTaxRate: z.number().min(0).max(0.2),
  firstTimeBuyer: z.boolean(),
  firstTimeBuyerThreshold: z.number().min(0),
  notaryAdvisorPct: z.number().min(0).max(0.1),
  nhg: z.boolean(),
  nhgThreshold: z.number().min(0),
  nhgPremiumPct: z.number().min(0).max(0.05),
  nhgRateReductionBps: z.number().min(0).max(500),
  interestOnly: z.boolean(),
  box3ThresholdGrowthPct: z.number().min(-0.2).max(0.5),
  wozGrowthPct: z.number().min(-0.2).max(0.5),
}).refine((d) => d.horizonYears <= d.termYears, {
  message: "horizon must be ≤ mortgage term",
  path: ["horizonYears"],
});
