import { z } from "zod";

export const usSchema = z.object({
  country: z.literal("us"),
  homePrice: z.number().positive(),
  downPaymentPct: z.number().min(0).max(1),
  mortgageRate: z.number().min(0).max(0.5),
  termYears: z.number().int().positive().max(40),
  horizonYears: z.number().int().positive().max(40),
  closingCostsPct: z.number().min(0).max(0.2),
  appreciationPct: z.number().min(-0.2).max(0.5),
  maintenancePct: z.number().min(0).max(0.1),
  insuranceAnnual: z.number().min(0),
  hoaMonthly: z.number().min(0),
  monthlyRent: z.number().min(0),
  rentInflationPct: z.number().min(-0.1).max(0.5),
  cpiPct: z.number().min(-0.1).max(0.5),
  equityReturnPct: z.number().min(-0.5).max(0.5),
  bondReturnPct: z.number().min(-0.5).max(0.5),
  equitySplit: z.number().min(0).max(1),
  filing: z.enum(["single", "mfj"]),
  stateLocalIncomeRate: z.number().min(0).max(0.5),
  federalMarginalRate: z.number().min(0).max(0.5),
  propertyTaxRate: z.number().min(0).max(0.1),
  pmiRate: z.number().min(0).max(0.05),
  standardDeductionSingle: z.number().min(0),
  standardDeductionMFJ: z.number().min(0),
  saltCap: z.number().min(0),
  acquisitionDebtCap: z.number().min(0),
  ltcgRate: z.number().min(0).max(0.5),
  niit: z.boolean(),
  standardDeductionGrowthPct: z.number().min(-0.2).max(0.5),
  saltCapGrowthPct: z.number().min(-0.2).max(0.5),
  acquisitionDebtCapGrowthPct: z.number().min(-0.2).max(0.5),
}).refine((d) => d.horizonYears <= d.termYears, {
  message: "horizon must be ≤ mortgage term",
  path: ["horizonYears"],
});
